version: '3'
services:
    nginx:
        container_name: sylius-nginx
        image: nginx:alpine
        restart: always
        ports:
            - "8088:80"
        networks:
            sylius:
                aliases:
                    - nginx.local
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./source:/var/www/html
    php-fpm:
        container_name: sylius-php
        build:
            context: ./php-fpm
        restart: always
        networks:
            sylius:
                aliases:
                    - fpm.local
        volumes:
            - ./source:/var/www/html
            - /home/partage:/var/www/partage
    db:
        container_name: sylius-db
        image: mariadb:10
        restart: always
        environment:
            MYSQL_DATABASE: sylius
            MYSQL_USER: sylius
            MYSQL_PASSWORD: sylius
            MYSQL_ROOT_PASSWORD: sylius
        networks:
            sylius:
                aliases:
                    - db.local
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./mariadb:/etc/mysql/conf.d
    redis:
        container_name: sylius-redis
        image: redis:alpine
        restart: always
        networks:
            sylius:
                aliases:
                    - redis.local
        volumes:
            - ./data/redis:/data
    node:
        container_name: sylius-node
        image: node:15.14.0
        restart: "no"
        networks:
            - sylius
        volumes:
            - ./source:/app
        working_dir: /app
        command: [ "yarn", "install" ]
    mailhog:
        container_name: sylius-mailhog
        image: mailhog/mailhog
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            sylius:
                aliases:
                    - mail.local
    adminer:
        image: adminer
        restart: "no"
        ports:
            - 8090:8080
        environment:
            ADMINER_PLUGINS: "json-column"
            ADMINER_DESIGN: "pappu687"
        networks:
            sylius:
                aliases:
                    - adminer.local

networks:
    sylius:
